"""Add Grade model, remove notification tables, add overall_grade to Student

Revision ID: cd6336f5b63b
Revises: 5628d724bf21
Create Date: 2024-10-17 12:27:19.439243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd6336f5b63b'
down_revision = '5628d724bf21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=2), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('student_notification')
    op.drop_table('parent_notification')
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overall_grade', sa.String(length=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('overall_grade')

    op.create_table('parent_notification',
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.Column('notification_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notification.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['parent.id'], )
    )
    op.create_table('student_notification',
    sa.Column('student_id', sa.INTEGER(), nullable=True),
    sa.Column('notification_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notification.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], )
    )
    op.drop_table('grade')
    # ### end Alembic commands ###
